import test from'node:test';import assert from'node:assert/strict';import{change,transform,isRate,correlation,pairs,validateSnapshot}from'../dist/assets/math.js';
const s=(unit,observations,frequency='monthly')=>({id:'test',unit,frequency,observations});
test('Una pendiente medida en pp cambia en pp, nunca porcentaje',()=>{const x=s('p.p.',[{date:'2026-09-17',value:.25},{date:'2026-09-18',value:.20}],'daily');assert.ok(isRate(x));assert.equal(change(x).unit,'pp');assert.ok(Math.abs(change(x).value+.05)<1e-10)});
test('YoY usa fecha calendario y respeta mes faltante',()=>{const x=s('índice',[{date:'2024-10-01',value:100},{date:'2024-11-01',value:110},{date:'2025-11-01',value:121}]);const y=transform(x,'yoy');assert.ok(Math.abs(y.at(-1).value-10)<1e-10);assert.equal(y[0].value,null)});
test('Tasa frente a año previo usa diferencia',()=>{const x=s('% interanual',[{date:'2025-08-01',value:2},{date:'2026-08-01',value:3}]);assert.equal(change(x,true).value,1);assert.equal(change(x,true).unit,'pp')});
test('Base negativa utiliza cambio absoluto',()=>{const x=s('Millones S/',[{date:'2026-07-01',value:-100},{date:'2026-08-01',value:-150}]);assert.equal(change(x).value,-50);assert.equal(change(x).unit,'Millones S/')});
test('Base100 alinea a la fecha pedida',()=>{const x=s('USD',[{date:'2020-01-01',value:20},{date:'2020-02-01',value:40},{date:'2020-03-01',value:50}]);assert.deepEqual(transform(x,'index','all','2020-02-01').map(x=>x.value),[100,125])});
test('Correlación excluye fechas no coincidentes y no acepta constantes',()=>{const a=[{date:'a',value:1},{date:'b',value:2},{date:'c',value:3}],b=[{date:'b',value:4},{date:'c',value:6}];assert.equal(pairs(a,b).length,2);assert.equal(correlation([{x:1,y:2},{x:1,y:4},{x:1,y:6}]),null)});
test('Una publicación inválida no puede sustituir la visible',()=>{assert.throws(()=>validateSnapshot({series:[s('%',[{date:'2026-01-01',value:1},{date:'2026-01-01',value:2}])]}));assert.throws(()=>validateSnapshot({series:[]}))});
